config/routes.rb
SecureSanta::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => 'events#new'

  get 'e/:admin_uid', to: 'events#show_admin', as: 'event_admin'
  get 'e/:admin_uid/edit', to: 'events#edit', as: 'edit_event'
  patch 'e/:admin_uid', to: 'events#update'
  delete 'e/:admin_uid', to: 'events#destroy'
  patch 'e/:admin_uid/assign_giftees', to: 'events#assign_giftees', as: 'assign_giftees_event'

  patch 'e/:admin_uid/p/:uid/reset_player', to: 'players#reset_player', as: 'reset_player'
  patch 'events/:event_id/players/:id/confirm', to: 'players#confirm', as: 'confirm_event_player'
  get 'p/:uid', to: 'players#show_verified', as: 'verified_player'
  patch 'p/:uid', to: 'players#update_verified'

  resources :events, :only => [:index, :show, :new, :create] do
    resources :players, :only => [:show, :show_verified]
  end

  get 'user', to: 'users#events', as: 'user'
  get 'user/events', to: 'users#events', as: 'user_events'

end

app/models/event.rb
require 'secure_santa/assigner'

class Event < ActiveRecord::Base

  has_many :players, inverse_of: :event, dependent: :destroy

  validates :name, presence: true, length: { maximum: 300 }
  validates :players, :nested_attributes_uniqueness => {:field => :name}
  validate :validate_date, if: :date_changed?

  accepts_nested_attributes_for :players, reject_if: lambda { |a| a[:name].blank? }, allow_destroy: true

  before_create :set_admin_uid

  def assign_giftees
    assigner = SecureSanta::Assigner.new players.to_a
    assignments = assigner.assign_giftees
    assignments.each do |player, giftee|
      player.update_attributes!(:giftee_id => giftee.id)
    end
  end

  def assigned?
    players.each do |player|
      return false if player.gifter.blank?
    end
    true
  end

  def players_claimed?
    players.all? { |p| p.claimed? }
  end

  def destroy_players!(players_attributes)
    return true unless players_attributes

    # Must destroy any players marked for destruction before other updates to avoid complicated validations
    destroy_keys = []
    players_attributes.each do |k, player_params|
      if ["true", "1"].include? player_params["_destroy"]
        player = Player.where(:id => player_params["id"]).last
        if player && player.event_id == self.id
          destroy_keys << k
          player.destroy
        end
      end
    end

    players_attributes.delete_if { |k| destroy_keys.include? k }

    true
  end

  def create_or_update_players(players_attributes)
    return true unless players_attributes

    players_attributes.each do |k, player_params|
      player = Player.where(:id => player_params["id"]).last
      if player_params && player_params["name"].present?
        if player
          raise "Cannot update a player of a different event!" if player.event_id != self.id
          # Update
          player.name = player_params["name"].strip
          player.save!
        else
          # Create
          Player.create!(:event => self, :name => player_params["name"].strip)
        end
      end
    end

    true
  end

  def set_admin_uid
    self.admin_uid = unique_admin_uid(10000000)
  end

  def unique_admin_uid(max_uid)
    all_uids = self.class.pluck(:admin_uid)
    tries = 10000
    digits = (max_uid - 1).to_s.size
    temp_uid = nil
    until (temp_uid && !all_uids.include?(temp_uid))
      temp_uid = rand(max_uid).to_s.rjust(digits, "0")
      tries -= 1
      if tries <= 0
        raise StandardError, "Too many events for UID range"
      end
    end
    temp_uid
  end

  def validate_date
    if date < 1.month.ago
      errors[:date] = "is too old"
    elsif date > 3.years.from_now
      errors[:date] = "is too far away"
    end
  rescue ArgumentError => e
    errors[:date] = "is invalid"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.order("created_at DESC")

    respond_to do |format|
      format.html
      format.json { render :json => @events }
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
    if @event.nil?
      redirect_to events_path, notice: "Could not find event." and return
    else
      if @event.admin_uid.blank?
        promote_to_event_admin
      else
        render :show
      end
    end
  end

  def show_admin
    @event = Event.find_by_admin_uid(params[:admin_uid])
    if @event.nil?
      redirect_to events_path, notice: "Could not find event." and return
    else
      render :show
    end
  end

  def new
  	@event = Event.new

    6.times { @event.players.build } # blank starting fields

    respond_to do |format|
      format.html
      format.json { render :json => @event }
    end
  end

  def create
    begin
      @event = Event.new(create_params)
    rescue ActionController::ParameterMissing => e
      Rails.logger.info "Parameter missing during event create. #{params}"
      return head(:bad_request)
    end

    if @event && @event.save
      flash[:error] = "Successfully created event.  Bookmark this page if you want to be able to edit it later!"
      redirect_to event_admin_path(@event.admin_uid)
    else
      flash[:error] = "Unable to create event."
      render :new
    end
  end

  def edit
    @event = Event.find_by_admin_uid(params[:admin_uid])
    if @event.nil?
      redirect_to events_path, error: "Could not find event." and return
    end
  end

  def update
    success = true
    @event = Event.find_by_admin_uid(params[:admin_uid])
    players_attributes = update_players_params["players_attributes"]
    if players_attributes
      players_attributes = mark_blank_name_deleted players_attributes
      success = @event.destroy_players!(players_attributes)
      success = @event.create_or_update_players(players_attributes) if success
    end
    success = @event.update_attributes(update_event_params) if success
    if success
      redirect_to event_admin_path(@event.admin_uid), notice: "Successfully updated event."
    else
      flash[:error] = "Unable to save edits."
      render :edit
    end
  end

  def destroy
    @event = Event.find_by_admin_uid(params[:admin_uid])
    if @event
      @event.destroy
      flash[:notice] = "Successfully deleted event."
    else
      flash[:error] = "Could not find event."
    end
    redirect_to events_path
  end

  def assign_giftees
    @event = Event.find_by_admin_uid(params[:admin_uid])
    begin
      @event.assign_giftees
      redirect_to event_admin_path(@event.admin_uid), notice: "Successfully assigned giftees!"
    rescue Exception => e
      Rails.logger.error e.inspect
      Rails.logger.error e.backtrace
      redirect_to event_admin_path(@event.admin_uid), error: "There was an error while assigning giftees."
    end
  end

  private

    def create_params
      params.require(:event).permit(:name, :date, players_attributes: [:name, :id, :_destroy])
    end

    def update_event_params
      params.require(:event).permit(:name, :date)
    end

    def update_players_params
      params.require(:event).permit(players_attributes: [:name, :id, :_destroy])
    end

    def promote_to_event_admin
      @event.set_admin_uid
      @event.save!
      flash[:error] = "You are now the event administrator.  Bookmark this page since there is no other way to edit the event later."
      redirect_to event_admin_path(@event.admin_uid) and return
    end

    def mark_blank_name_deleted players_attributes
      players_attributes.each do |k, player_params|
        if player_params["name"].blank?
          player_params["_destroy"] = "true"
        end
      end
      players_attributes
    end

end

app/helpers/events_helper.rb
module EventsHelper

    def player_role
      if params[:debug].present? && !Rails.env.production?
        Player::ROLE_SITE_ADMIN
      elsif params[:admin_uid]
        Player::ROLE_EVENT_ADMIN
      else
        super
      end
    end

end

app/views/events/_form.html.slim
.well
  - form_url = @event.admin_uid ? event_admin_path(@event.admin_uid) : @event
  = form_for(@event, url: form_url, html: { class: "form-horizontal" }) do |f|
    = render "shared/error_messages", :model_obj => @event

    .form-group
      = f.label :name, "Event Name", class: "col-sm-3 control-label"
      .col-sm-9 = f.text_field :name, placeholder: "Event Name", class: "form-control"

    .form-group
      = f.label :name, "Event Date", class: "col-sm-3 control-label"
      .col-sm-9
        = f.date_field :date, class: "form-control", placeholder: "mm/dd/yyyy"

    .players
      = f.fields_for :players do |builder|
        = render "player_fields", :f => builder

    .form-group
      .col-sm-9.col-sm-offset-3
        = link_to_add_fields("Add Invitee", f, :players).html_safe

    .form-group.actions
      .col-sm-9.col-sm-offset-3
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", @event, class: "btn"

app/views/events/_player_fields.html.slim
.form-group
  = f.label :name, "Invitee", class: "col-sm-3 control-label"
  .col-xs-9.col-sm-6 = f.text_field :name, placeholder: "Invitee", class: "form-control"
  .col-xs-3.col-sm-3
    p.form-control-static = link_to_remove_fields "remove", f

app/views/events/edit.html.slim
h1 Edit Event

= render "form"

app/views/events/index.html.slim
h1 All Events

.table-responsive
  table.table.table-striped
    tr
      th.hidden-phone Created on
      th Event
      th Event date
      th Giftees assigned
      th Players claimed
      - if player_role == Player::ROLE_SITE_ADMIN
        th Admin stuff
    - @events.each do |event|
      tr
        td.hidden-phone = event.created_at.to_date.to_formatted_s(:long)
        td = link_to event.name, event
        td = event.date ? event.date.to_formatted_s(:long) : ""
        td = event.assigned? ? "Yes" : "No"
        td = event.players_claimed? ? "Yes" : "No"
        - if player_role == Player::ROLE_SITE_ADMIN
          td
            = link_to "Admin page", event_admin_path(event.admin_uid) if event.admin_uid.present?

app/views/events/new.html.slim
h1 New Secret Santa Event

p 
  strong To start
  | , just name it, list the players, and click "Create Event"!

p 
  em Next, we'll give you a single message to copy and email to everyone, so all they have to do is click on the link with their name on it.

= render "form"

app/views/events/show.html.slim
h2
  | Event 
  = @event.name
  - if @event.date
    |  on #{@event.date.to_formatted_s(:long)}

- if @event.players.any?
  - if @event.assigned?
    p Everyone is assigned a secret santa!
  - else
    p Not everyone has a secret santa!  Click "Assign Giftees"!
- else
  p Click "Edit Event" to add players!

h2 Invitees
p Copy and paste this message into your email to send to everyone!
div.editable
  p
    | I'm inviting you to my Secret Santa event!
    br
    | Click "Claim or view this player" next to your name to start.
  ol
    - for player in @event.players.order("id asc")
      li
        = player.name
        |  - 
        - if player.uid.blank?
          = link_to "Claim or view this player", event_player_path(@event.id, player.id)
        - else
          = link_to "View this player", event_player_path(@event.id, player.id)
          |  (already claimed)
          - if [Player::ROLE_SITE_ADMIN, Player::ROLE_EVENT_ADMIN].include?(player_role)
            = form_for(player, url: reset_player_path(@event.admin_uid, player.uid), html: {method: "PATCH", style: "display:inline"}) do |f|
              |  - 
              = f.submit "Reset this player's secret link", class: "btn btn-link", style: "display:inline;padding:0;background:none", onclick: "confirm('Are you sure you want to reset #{player.name}?')"

- if player_role == Player::ROLE_SITE_ADMIN
  .assignments
    - if @event.assigned?
      h3 Assignments
      ol
        - for player in @event.players.order("id asc")
          li
            = link_to player.name, player.uid ? verified_player_path(player.uid) : event_player_path(@event, player)
            |  is giving to 
            = player.giftee.name

- if [Player::ROLE_SITE_ADMIN, Player::ROLE_EVENT_ADMIN].include?(player_role)
  .actions
    = link_to "Assign Giftees", { action: "assign_giftees" }, method: "patch", class: "btn btn-primary"
    = link_to "Edit Event", edit_event_path(@event.admin_uid), class: "btn btn-default"
    = link_to "Delete Event", {}, method: "delete", class: "delete-event", data: { confirm: 'Are you sure?' }