config/routes.rb
SecureSanta::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => 'events#new'

  get 'e/:admin_uid', to: 'events#show_admin', as: 'event_admin'
  get 'e/:admin_uid/edit', to: 'events#edit', as: 'edit_event'
  patch 'e/:admin_uid', to: 'events#update'
  delete 'e/:admin_uid', to: 'events#destroy'
  patch 'e/:admin_uid/assign_giftees', to: 'events#assign_giftees', as: 'assign_giftees_event'

  patch 'e/:admin_uid/p/:uid/reset_player', to: 'players#reset_player', as: 'reset_player'
  patch 'events/:event_id/players/:id/confirm', to: 'players#confirm', as: 'confirm_event_player'
  get 'p/:uid', to: 'players#show_verified', as: 'verified_player'
  patch 'p/:uid', to: 'players#update_verified'

  resources :events, :only => [:index, :show, :new, :create] do
    resources :players, :only => [:show, :show_verified]
  end

  get 'user', to: 'users#events', as: 'user'
  get 'user/events', to: 'users#events', as: 'user_events'

end

app/models/player.rb
class Player < ActiveRecord::Base

  ROLE_ANONYMOUS = :anonymous
  ROLE_EVENT_ADMIN = :event_admin
  ROLE_SITE_ADMIN = :site_admin

  belongs_to :event, inverse_of: :players

  belongs_to :gifter, class_name: "Player", foreign_key: "giftee_id"
  has_one :giftee, class_name: "Player", foreign_key: "giftee_id"

  belongs_to :user

  validates :name, presence: true, length: { maximum: 400 }
  validates :event, presence: true
  validate :giftee_same_event, if: lambda { giftee.present? }
  validates_uniqueness_of :name, scope: :event_id, message: "cannot be the same as another player in the event."

  def set_uid
    self.uid = unique_uid(10000000)
  end

  def unique_uid(max_uid)
    all_uids = self.class.pluck(:uid)
    tries = 10000
    digits = (max_uid - 1).to_s.size
    temp_uid = nil
    until (temp_uid && !all_uids.include?(temp_uid))
      temp_uid = rand(max_uid).to_s.rjust(digits, "0")
      tries -= 1
      if tries <= 0
        raise StandardError, "Too many players for UID range"
      end
    end
    temp_uid
  end

  def claimed?
    uid.present?
  end

  private

    def giftee_same_event
      if event != giftee.event
        errors.add(:giftee, "must belong to the same event")
      end
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player = Player.find_by_id(params[:id])
    redirect_to event_path(params[:event_id]), error: "Could not find player." and return unless @player
    redirect_to verified_player_path(@player.uid) and return if user_signed_in? && current_user == @player.user
    render :show
  end

  def show_verified
    @player = Player.find_by_uid(params[:uid])
    if @player.nil?
      flash[:notice] = "Could not find player."
      redirect_to events_path and return
    end
  end

  def confirm
    player = Player.find_by_id_and_event_id(params[:id], params[:event_id])
    redirect_to events_path, error: "Could not find player." and return unless player
    redirect_to player.event, notice: "Player #{player.name} has already claimed their secret page!" and return if player.claimed?
    return claim_and_redirect_to(player)
  end

  def reset_player
    event = Event.find_by_admin_uid(params[:admin_uid])
    redirect_to events_path, error: "Could not find event." and return unless event
    player = Player.find_by_uid(params[:uid])
    redirect_to event, error: "Could not find player." and return unless player
    player.update_attributes!(:uid => nil, :user_id => nil)
    redirect_to event_admin_path(event.admin_uid)
  end

  def update_verified
    player = Player.find_by_uid(params[:uid])
    if player.update_attributes(update_params)
      redirect_to verified_player_path(player.uid), notice: "Successfully updated player." and return
    else
      flash[:error] = "Unable to save edits."
      render :show_verified
    end
  end

  private

    def update_params
      params.require(:player).permit(:message, :user_id)
    end

    def claim_and_redirect_to(player)
      player.set_uid

      if user_signed_in?
        player.user = current_user
        flash[:notice] = "Successfully claimed player #{player.name}!"
      else
        flash[:error] = "Bookmark this secret page, there is no other way to get to it later!"
      end

      player.save!
      redirect_to verified_player_path(player.uid)
    end

end

app/views/players/_why_sign_in.html.slim
ul
  li You won't have to bookmark your secret URL
  li If you lose your secret URL you'll have to ask the event leader to reset it
  li We only save your Facebook ID and name
  li We do NOT save or even receive your email or friends list
  li We cannot post to your wall

app/views/players/show.html.slim
#show-player
  h3
    | Event 
    = link_to "#{@player.event.name}", @player.event
    - if @player.event.date
      |  on #{@player.event.date.to_formatted_s(:long)}

  - if @player.claimed?
    p This player is already claimed!
    - unless user_signed_in?
      p
        | If you claimed the user with Facebook, just click 
        = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
        |  to go to your Secret Santa page.
    p If you lost your secret URL, ask your event leader to reset it.
  - else
    - unless user_signed_in?
      .well
        = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
        br
        h5 Why should I sign in?
        = render "why_sign_in"

    = form_for(@player, url: confirm_event_player_path(@player.event_id, @player.id), html: {method: "PATCH"}) do |f|
      = f.submit "I am #{@player.name}, take me to my Secret Santa page.", class: 'btn btn-primary claim-user'

    = link_to "I am not #{@player.name}, take me back to the event page.", @player.event, class: 'btn btn-default no-claim-user'

app/views/players/show_verified.html.slim
#show-verified-player
  h3
    | Event 
    = link_to "#{@player.event.name}", @player.event
    - if @player.event.date
      |  on #{@player.event.date.to_formatted_s(:long)}

  h4
    | Secret Santa assignment for 
    = @player.name

  - if @player.giftee
    h2 You are giving to #{@player.giftee.name}!
  - else
    | The event leader has not yet clicked "Assign Giftees".  Bug them about it!

  - if @player.giftee && @player.giftee.message.present?
    h4 Message from your giftee:
    .well
      = text_area_tag "giftee_message", @player.giftee.message, disabled: true, style: "width:100%"

  h4 Write a message or wishlist to your secret santa:
  .well
    = form_for(@player, url: verified_player_path(@player.uid), html: {method: "PATCH"}) do |f|
      = f.text_area :message, value: @player.message, style: "width:100%"
      br
      = f.submit "Update message", :class => "btn btn-primary"

  - if @player.user.nil?
    p
      .well
        - if user_signed_in?
          = form_for(@player, url: verified_player_path(@player.uid), html: {method: "PATCH"}) do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.submit "Link this player to #{current_user.name}", class: "btn btn-primary"
          h5 Why should I link this player to Facebook?
        - else
          = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
          br
          h5 Why should I sign in?
        = render "why_sign_in"