config/routes.rb
SecureSanta::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => 'events#new'

  get 'e/:admin_uid', to: 'events#show_admin', as: 'event_admin'
  get 'e/:admin_uid/edit', to: 'events#edit', as: 'edit_event'
  patch 'e/:admin_uid', to: 'events#update'
  delete 'e/:admin_uid', to: 'events#destroy'
  patch 'e/:admin_uid/assign_giftees', to: 'events#assign_giftees', as: 'assign_giftees_event'

  patch 'e/:admin_uid/p/:uid/reset_player', to: 'players#reset_player', as: 'reset_player'
  patch 'events/:event_id/players/:id/confirm', to: 'players#confirm', as: 'confirm_event_player'
  get 'p/:uid', to: 'players#show_verified', as: 'verified_player'
  patch 'p/:uid', to: 'players#update_verified'

  resources :events, :only => [:index, :show, :new, :create] do
    resources :players, :only => [:show, :show_verified]
  end

  get 'user', to: 'users#events', as: 'user'
  get 'user/events', to: 'users#events', as: 'user_events'

end

app/views/layouts/_navbar.html.slim
.navbar.navbar-inverse.navbar-static-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"
        | Secure Santa
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li = link_to "New Event", new_event_path
        li = link_to "All Events", events_path
      ul.nav.navbar-nav.navbar-right
        li.user-menu
          - if user_signed_in?
            a.dropdown-toggle href="#" data-toggle="dropdown"
              = image_tag avatar_url, title: "Signed in as #{current_user.name}", class: "avatar img-thumbnail"
              span.caret
            ul.dropdown-menu
              li = link_to "My events".html_safe, user_path
              li = link_to "Sign out", users_sign_out_path, :method => :delete
          - else
            = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    meta name="keywords" content="secure santa, secret santa"
    meta name="author" content="Michael Kozono"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  body
    = render "layouts/navbar"

    .container
      #content
        = render "shared/flash_messages"
        == yield

      #footer
        | Copyright © #{Time.now.year} Michael Kozono